platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: goof

outputs:
  - name: build
    path: build

caches:
- path: goof/node_modules

run:
  path: sh
  args:
  - -exec
  - cd goof && npm install
