platform: linux

image_resource:
  type: docker-image
  source:
    repository: snyk/snyk-cli
    tag: latest

params:
  SNYK_TOKEN: embedded
  PROJECT_PATH: 'goof'
  FAIL_BUILD: false
inputs:
  - name: goof
  - name: npm-repo-cache
    path: /cache

run:
  path: goof/ci/scripts/run_snyk.sh
