resource_types:
  - name: snyk-test
    type: docker-image
    source:
      repository: snyk/snyk-cli
      tag: latest

  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: latest}

resources:
  - name: goof
    type: git
    source:
      uri: https://github.com/ah7/goof
      branch: master

  - name: npm-repo-cache
    type: npm-cache
    source:
      uri: https://github.com/ah7/goof.git
      branch: master
      paths:
        - package.json

  - name: resource-deploy-app
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}

jobs:
  - name: build
    plan:
      - get: goof
        trigger: true
      - get: npm-repo-cache

  - name: test
    plan:
      - get: goof
        trigger: true
        passed: [build]
      - get: npm-repo-cache
        passed: [build]
      - task: test suite
        file: goof/ci/tasks/run_tests.yml
  - name: security
    plan:
      - get: goof
        trigger: true
        passed: [test]
      - get: npm-repo-cache
        passed: [build]
      - task: snyk test
        file: goof/ci/tasks/run_snyk.yml
        params:
          SNYK_TOKEN: {{snyk_token}}
  - name: deploy
    plan:
      - get: goof
        trigger: true
        passed: [security]
      - put: resource-deploy-app
        params:
          manifest: goof/manifest.yml
